server:
  port: 7000

spring:
  application:
    name: gateway-service
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      discovery:
        username: nacos
        password: nacos
        namespace: public
    gateway:
      routes:
        - id: product_route
          uri: lb://product-service
          order: 1
          predicates:
            - Path=/product-serv/**
          filters:
            - StripPrefix=1
        - id: order_route
          uri: lb://order-service
          order: 1
          predicates:
            - Path=/order-serv/**
          filters:
            - StripPrefix=1
      discovery:
        locator:
          enabled: true

stock-service:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule